package learning;
import java.util.Scanner;
import java.util.Random;
class game{
	public int num;  // num is the number which stores the random number generated by computer
	public int userNum;
	public int count;
	Scanner s=new Scanner(System.in);
	public void createRandomNumber(){
		//num=(int)(Math.random()*101);
		Random rand=new Random();
		num=rand.nextInt(100);
	}
	
	public int getNum(){
		return num;
	}
	
	public void show(){
		count++;
		System.out.println("Hey user,guess the number? ");
		userNum=s.nextInt();
		setNumber(userNum);
	}
	
	public void setNumber(int n){
		userNum=n;
		matching();
	}
	
	public void matching(){
		if(userNum==num)
			System.out.println("Congratulations! You have guess the number and your choice count is "+count);
		else{
			if(userNum>num)
				System.out.println("OOPs! Choice is >bigger,try again with a smaller number...");
				
			else
				System.out.println("OOPs! Choice is <smaller,try with a bigger number...");
			
			show();
		}
			
	}
}
public class GuessTheNumber {

	public static void main(String[] args){
		/* Create a class game which allows a user to play "Guess the Number" game once.
		  Game should have the following methods:
		Constructor to generate the random number
		takeUserInput() to take a user input of number
		isCorrectNumber() to detect whether the number entered by the user is true
		getter and setter for noOfGuesses
		Use properties such as noOfGuesses(int), etc to get this task done! */
		
		Scanner sc=new Scanner(System.in);
		game myGame=new game();
		myGame.createRandomNumber();
		System.out.println("Hey user, guess the number? ");
		int num=sc.nextInt();
		myGame.setNumber(num);
		//myGame.matching();
		//System.out.println(myGame.getNum());
	}
}
